
name: PushToMain - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
 
 push:
    branches: [ main ]

jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Run Project Tests
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v1
        with:
          command: lastpush="${{ github.event.before }}", diffGitHub_push(lastpush)
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v3
        with:
           name: diffreports
           path: ${{ github.workspace }}\*.html
      - name: Run All Project Tests
        uses: matlab-actions/run-command@v1
        with:
          command: runtests

#   Copyright 2022 The MathWorks, Inc.
